meta_product_name: "Pimprenelle"
meta_title: "Pimprenelle: Histoires pour Enfants à Lire et Écouter"
meta_description: "Pimprenelle est l'application mobile idéale pour les parents qui souhaitent trouver facilement des histoires captivantes à lire ou écouter pour leurs enfants. Offrant une sélection variée de contes et récits, Pimprenelle stimule l'imagination et l'éveil des petits tout en facilitant la vie des parents."
meta_image: "pimprenelle_logo.png"
